elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
kibana:
  image: kibana
  links:
    - elasticsearch
  ports:
    - "5601:5601"
logstash:
  build: ./images/logstash
  links:
    - elasticsearch
  volumes:
    - ./logs:/logs
packetbeat:
  build: ./images/packetbeat
  net: "host"
topbeat:
  image: athieriot/topbeat
  links:
    - elasticsearch
  pid: "host"
